version: '2'

services:
  dockerui:
    image: uifd/ui-for-docker:${DOCKERUI_VERSION}
    hostname: dockerui.${URL_SUFFIX}
    privileged: true
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#    ports:
#      - "${DOCKERUI_PORT_FROM}:${DOCKERUI_PORT_TO}"
