version: '2'

services:
  onlyoffice-document-server:
    image: onlyoffice/documentserver
    #hostname: docs.${ONLYOFFICE_NAME_SERVER}
    hostname: docs.office.${URL_SUFFIX}
    restart: unless-stopped
    volumes:
      - ${ONLYOFFICE_DOCS}:/var/www/onlyoffice/Data
      - ${ONLYOFFICE_LOGS}:/var/log/onlyoffice
    dns:
      - 208.67.220.220
      - 8.8.4.4
      - 208.67.222.222
      - 8.8.8.8
