#!/bin/bash

source setup


if [[ ! -f "${OVPN_CONFIG}/pki/private/${OVPN_CLIENT_NAME}.key" ]]; then
rm ${OVPN_CONFIG}/pki/issued/${OVPN_CLIENT_NAME}.crt  || true
rm ${OVPN_CONFIG}/pki/private/${OVPN_CLIENT_NAME}.key || true
rm ${OVPN_CONFIG}/pki/reqs/${OVPN_CLIENT_NAME}.req    || true
docker run --volume=${OVPN_VOL_MAP} --rm -it                                                               kylemanna/openvpn easyrsa build-client-full ${OVPN_CLIENT_NAME}
fi


if [[ ! -f "${OVPN_CONFIG}/${OVPN_CLIENT_NAME}.ovpn" ]]; then
docker run --volume=${OVPN_VOL_MAP} --rm                                                                   kylemanna/openvpn ovpn_getclient ${OVPN_CLIENT_NAME} > ${OVPN_CONFIG}/${OVPN_CLIENT_NAME}.ovpn
fi

echo "copy profile on ${OVPN_CONFIG}/${OVPN_CLIENT_NAME}.ovpn"
