version: '2'

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge

services:
  nginx:
    extends:
      file: nginx.yml
      service: nginx
    networks:
    - default
    - back-tier
    - front-tier


