version: '2'

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge

services:
  gitlab-redis:
    extends:
      file: gitlab.yml
      service: gitlab-redis

  gitlab-postgresql:
    extends:
      file: gitlab.yml
      service: gitlab-postgresql

  gitlab:
    extends:
      file: gitlab.yml
      service: gitlab
    links:
      - gitlab-redis:redis
      - gitlab-postgresql:postgresql
