version: '2'

services:
  gitlab-postgresql:
    restart: unless-stopped
    #restart: always
    image: sameersbn/postgresql:${GITLAB_POSTGRES_VERSION}
    environment:
      - DB_USER=${GITLAB_POSTGRES_USER}
      - DB_PASS=${GITLAB_POSTGRES_PASS}
      - DB_NAME=${GITLAB_POSTGRES_NAME}
      - DB_EXTENSION=pg_trgm
    volumes:
      - ${GITLAB_POSTGRES_DATA}:/var/lib/postgresql:Z

  gitlab-redis:
    restart: unless-stopped
    #restart: always
    command:
    - --loglevel warning
    image: sameersbn/redis:latest
    volumes:
      - ${GITLAB_REDIS_DATA}:/var/lib/redis:Z

  gitlab:
    restart: unless-stopped
    image: sameersbn/gitlab:${GITLAB_VERSION}
    hostname: gitlab.${URL_SUFFIX}
#    links:
#      - gitlab-redis:redisio
#      - gitlab-postgresql:postgresql
    ports:
      - ${GITLAB_PORT_FROM_1}:${GITLAB_PORT_TO_1}
#      - ${GITLAB_PORT_FROM_2}:${GITLAB_PORT_TO_2}
#      - ${GITLAB_PORT_FROM_3}:${GITLAB_PORT_TO_3}
    environment:
      - DEBUG=false
      - TZ=Europe/Amsterdam
      - GITLAB_TIMEZONE=Amsterdam

      - DB_ADAPTER=postgresql
      - DB_HOST=postgresql
      - DB_PORT=5432

      - DB_USER=${GITLAB_POSTGRES_USER}
      - DB_PASS=${GITLAB_POSTGRES_PASS}
      - DB_NAME=${GITLAB_POSTGRES_NAME}

      - REDIS_HOST=redis
      - REDIS_PORT=6379

      - GITLAB_SECRETS_DB_KEY_BASE=${GITLAB_SECRETS_DB}
      - GITLAB_SECRETS_SECRET_KEY_BASE=${GITLAB_SECRETS_SECRET}
      - GITLAB_SECRETS_OTP_KEY_BASE=${GITLAB_SECRETS_OTP}

      - GITLAB_PORT=${GITLAB_PORT}
      - GITLAB_SSH_PORT=${GITLAB_SSH_PORT}
      - GITLAB_HTTPS=${GITLAB_HTTPS}
      - GITLAB_PROJECTS_VISIBILITY=${GITLAB_PROJECTS_VISIBILITY}
      - GITLAB_BACKUPS=${GITLAB_BACKUPS}
      - GITLAB_BACKUP_EXPIRY=${GITLAB_BACKUP_EXPIRY}

      #- GITLAB_HOST=localhost
      #- GITLAB_PORT=10080
      #- GITLAB_SSH_PORT=10022
      #- GITLAB_RELATIVE_URL_ROOT=

      #- GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
      #- GITLAB_NOTIFY_PUSHER=false

      #- GITLAB_EMAIL=notifications@example.com
      #- GITLAB_EMAIL_REPLY_TO=noreply@example.com
      #- GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com

      - GITLAB_BACKUP_SCHEDULE=daily
      - GITLAB_BACKUP_TIME=01:00

      - SMTP_ENABLED=false
      - SMTP_DOMAIN=www.example.com
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=mailer@example.com
      - SMTP_PASS=password
      - SMTP_STARTTLS=true
      - SMTP_AUTHENTICATION=login

      - IMAP_ENABLED=false
      - IMAP_HOST=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USER=mailer@example.com
      - IMAP_PASS=password
      - IMAP_SSL=true
      - IMAP_STARTTLS=false
    volumes:
      - ${GITLAB_DATA}:/home/git/data:Z
      #- /srv/docker/gitlab/gitlab:/home/git/data


#  gitlab:
#    image: sameersbn/gitlab:${GITLAB_VERSION}
#    hostname: gitlab.aflitos.net
#    restart: unless-stopped
#    volumes:
#     - ${GITLAB_DATA}:/home/git/data
#      - ${GITLAB_SQL}:/var/lib/mysql
#    ports:
#      - ${GITLAB_PORT_FROM_1}:${GITLAB_PORT_TO_1}
#      - ${GITLAB_PORT_FROM_2}:${GITLAB_PORT_TO_2}
#      - ${GITLAB_PORT_FROM_3}:${GITLAB_PORT_TO_3}
#    environment:
#      - GITLAB_PORT=${GITLAB_PORT}
#      - GITLAB_SSH_PORT=${GITLAB_SSH_PORT}
#      - GITLAB_HTTPS=${GITLAB_HTTPS}
#      - GITLAB_PROJECTS_VISIBILITY=${GITLAB_PROJECTS_VISIBILITY}
#      - GITLAB_BACKUPS=${GITLAB_BACKUPS}
#      - GITLAB_BACKUP_EXPIRY=${GITLAB_BACKUP_EXPIRY}


